// flow-typed signature: 4e78ea59600debd7304350981ef9a51e
// flow-typed version: <<STUB>>/gulp-webp_v^3.0.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-webp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-webp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-webp/index' {
  declare module.exports: $Exports<'gulp-webp'>;
}
declare module 'gulp-webp/index.js' {
  declare module.exports: $Exports<'gulp-webp'>;
}
